name: Publish

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: "Setup Rust"
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy
      - name: Download circom
        run: wget https://github.com/iden3/circom/releases/latest/download/circom-linux-amd64 -O /usr/local/bin/circom
      - name: Update permission
        run: chmod +x /usr/local/bin/circom
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Publish binaries
        run: yarn package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
